[package]
name = "tymp"
version = "0.1.2"
edition = "2021"

[features]
chunks_8 = []
chunks_64 = []
chunks_128 = []
copy = []
default = ["chunks_64", "copy"]

[dependencies]
cfg-if = "1.0.0"
discard-while = "0.1.0"
