[package]
name = "tymp"
version = "0.1.2"
edition = "2021"

[features]
chunks_8 = []
chunks_64 = []
chunks_128 = []
default = ["chunks_64"]

[dependencies]
cfg-if = "1.0.0"
itertools = { version = "0.10.5", default-features = false }
